name: persona
favicon: null
layout_spectrum: 0.15276
typography_spectrum: 0.37562
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#525252'
    - '#8f8f8f'
    - '#c5c5c5'
    - '#f9f9f9'
  brandStrength: 0
  lightness: 0.125
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
