name: persona
favicon: null
layout_spectrum: 0.15276
typography_spectrum: 0.7299968781881034
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.847615580772981
  lightness: 0.6176700394134969
  saturation: 0.6524179857224226
  rhythmicContrast: 0.028208749601617455
purpose: []
