name: persona
favicon: null
layout_spectrum: 0.49833
typography_spectrum: 0.37562
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#262f3e'
    - '#010206'
    - '#48515a'
    - '#dec2aa'
    - '#ab7769'
  brandStrength: 0
  lightness: 0.125
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
